administrador/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # ADMIN-DJANGO
    path('admin/', admin.site.urls),

    # APLICACION USUARIO
    path('', include('gestion_usuarios.urls')),

    # APLICACION REPOSITORIO DE TITULADOS
    path('', include('repositoriotitulados.urls')),
    
    # APLICACION SEG_MOD_GRADUACION
    path('', include('seg_mod_graduacion.urls')),
    
    # APLICACIION INTERACCION SOCIAL
    path('', include('interaccion_social.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

seg_mod_graduacion/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler403
from .views import handle_permission_denied
from seg_mod_graduacion import views
from .views import ModalidadCreateView, ModalidadListView, ModalidadUpdateView, Pdf_ReporteActaPrivada, Pdf_ReporteActaPublica
from .views import pdf_reporteinv,Pdf_Reporte_InvFiltrado, Pdf_Reporte_Perfiles, Pdf_ReporteActa

urlpatterns = [    
    #segguimiento modalidad de graduacion investigacion cientifica
    path('invcientifica/agregar_investigacion/', views.agregar_investigacion, name='agregar_investigacion'),
    path('invcientifica/vista_investigacion/',views.vista_investigacion, name='vista_investigacion'),
    path('invcientifica/ProyectosParaAprobar/', views.ProyectosParaAprobar.as_view(), name='ProyectosParaAprobar'),
    path('AprobarProyecto/<int:proyecto_id>/', views.AprobarProyecto.as_view(), name='AprobarProyecto'),
    path('RechazarProyecto/<int:proyecto_id>/', views.RechazarProyecto.as_view(), name='RechazarProyecto'),
    path('invcientifica/global_settings/', views.global_settings_view, name='global_settings'),
    path('listarinvcientifica/', views.listarinvcientifica, name='listarinvcientifica'),
    path('pdf_reporteinv/<int:pk>/', pdf_reporteinv.as_view(), name='pdf_reporteinv'),
    path('Pdf_Reporte_InvFiltrado', Pdf_Reporte_InvFiltrado.as_view(), name='Pdf_Reporte_InvFiltrado'),
    
    #seguimiento modalidad de graduacion perfil de proyecto
    path('perfil/agregar_perfil/', views.agregar_perfil, name='agregar_perfil'),
    path('perfil/vista_perfil/',views.vista_perfil, name='vista_perfil'),
    path('perfil/PerfilesParaAprobar/', views.PerfilesParaAprobar.as_view(), name='PerfilesParaAprobar'),
    path('AprobarPerfil/<int:proyecto_id>/', views.AprobarPerfil.as_view(), name='AprobarPerfil'),
    path('RechazarPerfil/<int:proyecto_id>/', views.RechazarPerfil.as_view(), name='RechazarPerfil'),
    path('agregar-acta/', views.agregar_actaperfil, name='agregar_actaperfil'),
    path('listarperfiles/', views.listarperfiles, name='listarperfiles'),
    path('reporte-perfiles-pdf/', Pdf_Reporte_Perfiles.as_view(), name='Pdf_Reporte_Perfiles'),
    path('perfil/astas_list', views.actaperfil_list, name='actaperfil_list'),
    path('reporte_acta/<int:pk>/', Pdf_ReporteActa.as_view(), name='Pdf_ReporteActa'),
    
    #seguimiento modalidad de graduacion proyecto final
    path('controlador/actividad_control/nueva/', views.crear_actividad_control, name='crear_actividad_control'),
    path('controlador/editar_actividad_control/<int:pk>/editar/', views.editar_actividad_control, name='editar_actividad_control'),
    path('controlador/lista_actividad_control/', views.lista_actividad_control, name='lista_actividad_control'),
    
    path('proyectofinal/revision/<int:actividad_id>/', views.revisar_actividad, name='revisar_actividad'),
    path('controlador/revision/<int:actividad_id>/', views.revision, name='revision'),
    
    path('controlador/listaractividades/', views.listaractividades, name='listaractividades'),
    path('controlador/listaactividades/', views.listaactividades, name='listaactividades'),
    
    path('proyectofinal/crear_actividad/nueva/', views.crear_actividad, name='crear_actividad'),
    path('proyectofinal/actividad/', views.lista_actividad, name='lista_actividad'),
    path('agregar-actaprivada/', views.agregar_actaprivada, name='agregar_actaprivada'),
    path('agregar-actapublica/', views.agregar_actapublica, name='agregar_actapublica'),
    path('buscar_estudiante_privada/', views.buscar_estudiante_privada, name='buscar_estudiante_privada'),
    path('buscar_estudiante_publica/', views.buscar_estudiante_publica, name='buscar_estudiante_publica'),
    path('buscar_estudiante_paractivar/', views.buscar_estudiante_paractivar, name='buscar_estudiante_paractivar'),
    path('proyectofinal/astas_list_privada', views.actaprivada_list, name='actaprivada_list'),
    path('proyectofinal/astas_list_publica', views.actapublica_list, name='actapublica_list'),
    path('reporte_acta_privada/<int:pk>/', Pdf_ReporteActaPrivada.as_view(), name='Pdf_ReporteActaPrivada'),
    path('reporte_acta_publica/<int:pk>/', Pdf_ReporteActaPublica.as_view(), name='Pdf_ReporteActaPublica'),
    
    path('modalidad/modalidadagregar/', ModalidadCreateView.as_view(), name='modalidadagregar'),
    path('modalidades/', ModalidadListView.as_view(), name='listarmodalidades'),
    path('modalidad/editarmodalidad/<int:pk>/', ModalidadUpdateView.as_view(), name='editarmodalidad'),
    
    path('reportes/home_reporte', views.home_reporte, name='home_reporte'),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler403 = handle_permission_denied

seg_mod_graduacion/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model
from datetime import date
from django.conf import settings
from django.core.exceptions import ValidationError  

User = get_user_model()

ESTADO_CHOICES = [
    ('Aprobado', 'Aprobado'),
    ('Pendiente', 'Pendiente'),
    ('Rechazado', 'Rechazado'),
]

FACULTAD_CHOICES = [
    ('INGENIERÍA Y TECNOLOGÍA', 'Ingeniería y Tecnología'),
    ('mas..', 'mas..'),
    # Agrega más opciones según sea necesario
]

CARRERA_CHOICES = [
   ('INGENIERÍA DE SISTEMAS', 'Ingeniería de Sistemas'),
    ('mas..', 'mas..'),
    # Agrega más opciones según sea necesario
]

RESULTADO_CHOICES = [
    ('Suficiente', 'Suficiente'),
    ('Insuficiente', 'Insuficiente'),
    ('Aprobado', 'Aprobado'),
    ('Reprobado', 'Reprobado'),
    ('Postergado', 'Postergado')
]

class Modalidad(models.Model):
    nombre = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    
    class Meta:
        verbose_name_plural = "Modalidades"
        verbose_name = "Modalidad"


    def __str__(self):
        return self.nombre

class InvCientifica(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Usuario relacionado')
    invtitulo = models.CharField(max_length=450, verbose_name='Agregar Titulo')
    slug = models.SlugField(unique=True)
    invfecha_creacion = models.DateTimeField(auto_now_add=True)
    invdescripcion = models.TextField(verbose_name='Agregar una Descripcion Breve', blank=True)
    invdocumentacion = models.FileField(upload_to='documento/investigacion', verbose_name='Agregar Documentacion', null=True, blank=True)
    investado = models.CharField(max_length=10, choices=ESTADO_CHOICES, default='Pendiente')
    
    class Meta:
        verbose_name_plural = "Investicaciones cientificas"
        verbose_name = "Investigacion cientifica"


    def __str__(self):
        return self.invtitulo

class ComentarioInvCientifica(models.Model):
    invcomentario = models.TextField(max_length=1000, help_text='', verbose_name='Ingrese Comentario Retroalimentativo')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    invfecha_post = models.DateTimeField(auto_now_add=True)
    invproyecto_relacionado = models.ForeignKey(InvCientifica, on_delete=models.CASCADE)
    invdocorregido = models.FileField(upload_to='documento/investigacion', verbose_name='Agregar Documentacion', null=True, blank=True)

    class Meta:
        verbose_name_plural = "Comentario InvCientifica"
        verbose_name = "Comentario Inv"
        ordering = ['-invfecha_post']

    def __str__(self):
        return self.invcomentario[:15] + '...' if len(self.invcomentario) > 15 else self.invcomentario

class HabilitarSeguimiento(models.Model):
    habilitarInv = models.BooleanField(default=True, verbose_name='Habilitar Formulario')
    
    class Meta:
        verbose_name_plural = "Habilitacion Inv"
        verbose_name = "Habilitar Inv"

    def __str__(self):
        return "Configuración Global"

class PerfilProyecto(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Usuario relacionado')
    pertitulo = models.CharField(max_length=450, verbose_name='Agregar Titulo Perfil')
    slug = models.SlugField(unique=True)
    perfecha_creacion = models.DateTimeField(auto_now_add=True)
    perdescripcion = models.TextField(verbose_name='Agregar una Descripcion', blank=True)
    perdocumentacion = models.FileField(upload_to='documento/perfil', verbose_name='Agregar Documentacion', null=True, blank=True)
    permodalidad = models.ForeignKey(Modalidad, on_delete=models.CASCADE, verbose_name='Seleccione Una Modalidad')
    perestado = models.CharField(max_length=10, choices=ESTADO_CHOICES, default='Pendiente')
    
    class Meta:
        verbose_name_plural = "Perfil de Proyectos"
        verbose_name = "Perfil Proyecto"

    def __str__(self):
        return self.pertitulo

class ComentarioPerfil(models.Model):
    percomentario = models.TextField(max_length=1000, help_text='', verbose_name='Ingrese Comentario Retroalimentativo')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    perfecha_post = models.DateTimeField(auto_now_add=True)
    perproyecto_relacionado = models.ForeignKey(PerfilProyecto, on_delete=models.CASCADE, related_name='comentarios')
    perdocorregido = models.FileField(upload_to='documento/perfil', verbose_name='Agregar Documentacion', null=True, blank=True)

    class Meta:
        verbose_name_plural = "Comentario Perfiles"
        verbose_name = "Comentario Perfil"
        ordering = ['-perfecha_post']

    def __str__(self):
        return self.percomentario[:15] + '...' if len(self.percomentario) > 15 else self.percomentario
 
class ActaGeneral(models.Model):
    perperiodo = models.CharField(max_length=50,null=True, blank=True )
    acta = models.CharField(max_length=30)
    facultad = models.CharField(max_length=100, choices=FACULTAD_CHOICES, default='INGENIERÍA Y TECNOLOGÍA')
    carrera = models.CharField(max_length=100, choices=CARRERA_CHOICES, default='INGENIERÍA DE SISTEMAS')
    estudiante = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='acta_estudiante', on_delete=models.CASCADE)
    titulo = models.CharField(max_length=450)
    lugar = models.CharField(max_length=50)
    fechadefensa = models.DateField(default=timezone.now)
    horainicio = models.TimeField()
    horafin = models.TimeField()
    tutor = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='acta_tutor', on_delete=models.CASCADE)
    jurado_1 = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='acta_jurado_1', on_delete=models.CASCADE)
    jurado_2 = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='acta_jurado_2', on_delete=models.CASCADE)
    jurado_3 = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='acta_jurado_3', on_delete=models.CASCADE)
    modalidad = models.ForeignKey('Modalidad', on_delete=models.CASCADE, verbose_name='Seleccione Una Modalidad')
    resultado = models.CharField(max_length=15, choices=RESULTADO_CHOICES, default='Suficiente')
    observacion_1 = models.TextField(max_length=200)
    observacion_2 = models.TextField(max_length=200)
    observacion_3 = models.TextField(max_length=200)
    
    class Meta:
        verbose_name_plural = "Actas Base General"
        verbose_name = "Base Actas"
        
    def __str__(self):
        return self.acta
    
class ActaProyectoPerfil(ActaGeneral):
    pass
    
    class Meta:
        verbose_name_plural = "Actas Defensa Perfiles"
        verbose_name = "Acta Perfil"
        
    def save(self, *args, **kwargs):
        # Aquí no llamas a super().save() si no quieres que ActaGeneral se guarde
        # Asegúrate de manejar la lógica de guardado necesaria solo para ActaPrivada
        if not self.pk:  # Es una nueva instancia
            self.acta = f"Perfil-{self.acta}"  # Personaliza según tu lógica
        super(ActaGeneral, self).save(*args, **kwargs)

class ActaPrivada(ActaGeneral):
    calificacion1 = models.IntegerField()
    
    class Meta:
        verbose_name_plural = "Actas defensa Privada"
        verbose_name = "Acta Privada"
    
    def save(self, *args, **kwargs):
        # Aquí no llamas a super().save() si no quieres que ActaGeneral se guarde
        # Asegúrate de manejar la lógica de guardado necesaria solo para ActaPrivada
        if not self.pk:  # Es una nueva instancia
            self.acta = f"Privada-{self.acta}"  # Personaliza según tu lógica
        super(ActaGeneral, self).save(*args, **kwargs)
    
class ActaPublica(ActaGeneral):
    calificacion1 = models.IntegerField()
    calificacion2 = models.IntegerField()
    notatotal = models.IntegerField()
    presidenteacta = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='acta_presidente_Asig', on_delete=models.CASCADE)
    
    class Meta:
        verbose_name_plural = "Actas Defensa Publica"
        verbose_name = "Acta Publica"
    
    def save(self, *args, **kwargs):
        # Aquí no llamas a super().save() si no quieres que ActaGeneral se guarde
        # Asegúrate de manejar la lógica de guardado necesaria solo para ActaPrivada
        if not self.pk:  # Es una nueva instancia
            self.acta = f"Publica-{self.acta}"  # Personaliza según tu lógica
        super(ActaGeneral, self).save(*args, **kwargs)

class HabilitarProyectoFinal(models.Model):
    estudiante = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='actividad_estudiante', on_delete=models.CASCADE)
    tutor = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='actividad_tutor', on_delete=models.CASCADE)
    jurado_1 = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='actividad_jurado_1', on_delete=models.CASCADE)
    jurado_2 = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='actividad_jurado_2', on_delete=models.CASCADE)
    jurado_3 = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='actividad_jurado_3', on_delete=models.CASCADE)
    modalidad = models.ForeignKey(Modalidad, on_delete=models.CASCADE,  verbose_name='Seleccione Una Modalidad')

    def habilitar_actividad(self):
        actividad, created = ProyectoFinal.objects.get_or_create(
            estudiante=self.estudiante,
            defaults={
                'tutor': self.tutor,
                'jurado_1': self.jurado_1,
                'jurado_2': self.jurado_2,
                'jurado_3': self.jurado_3,
                'modalidad': self.modalidad,
                'habilitada': True
            }
        )
        if not created:
            actividad.tutor = self.tutor
            actividad.jurado_1 = self.jurado_1
            actividad.jurado_2 = self.jurado_2
            actividad.jurado_3 = self.jurado_3
            actividad.modalidad = self.modalidad
            actividad.habilitada = True

seg_mod_graduacion/templates/perfil/actaperfil_list.html
{% extends 'dashboard.html' %}
{% load static %}
{% block content %}
<div class="container no-gutters px-lg-5 px-3">
    <h1 class="titlesuperior colortext py-4">Reporte Investigaciones Científicas
        <svg xmlns="http://www.w3.org/2000/svg" width="46" height="46" fill="currentColor" class="bi bi-mortarboard-fill" viewBox="0 0 16 16">
            <path d="M8.211 2.047a.5.5 0 0 0-.422 0l-7.5 3.5a.5.5 0 0 0 .025.917l7.5 3a.5.5 0 0 0 .372 0L14 7.14V13a1 1 0 0 0-1 1v2h3v-2a1 1 0 0 0-1-1V6.739l.686-.275a.5.5 0 0 0 .025-.917z"/>
            <path d="M4.176 9.032a.5.5 0 0 0-.656.327l-.5 1.7a.5.5 0 0 0 .294.605l4.5 1.8a.5.5 0 0 0 .372 0l4.5-1.8a.5.5 0 0 0 .294-.605l-.5-1.7a.5.5 0 0 0-.656-.327L8 10.466z"/>
        </svg>
    </h1>
    
    <!-- Formulario de búsqueda -->
    <form method="GET" action="">
        <div class="row">
            <div class="col-lg-10 col-8 form-group">
                <input type="text" name="q" class="form-control" placeholder="Buscar por nombre del estudiante">
            </div>
            <div class="col-lg-1 col-3 mt-1">
                <button type="submit" class="btn btn-dark px-lg-3">Buscar</button>
            </div>
        </div>
    </form>
   
    <hr>
    
    <!-- Mostrar todas las actividades científicas relacionadas -->
    {% for acta in actas %}
    <div class="no-gutte mb-5 fontI">
        <div class="row py-5">
            <div class="col-md-9 px-5 text-wrap">
                <!-- Your existing content for displaying actas -->
                <div class="row">
                    <div class="col-lg-4 col-12 text-center">
                        <p class="fecha colortext ">Fecha: <span class="colorestados">{{ acta.fechadefensa }} - {{ acta.lugar }}</span></p>
                    </div>
                    <div class="col-lg-4 col-12 text-center">
                        <p class="fecha colortext ">Hora de: <span class="colorestados"> {{ acta.horainicio }}</span> a: <span class="colorestados"> {{ acta.horafin }}</span></p>
                    </div>
                    <div class="col-lg-4 col-12 text-center">
                        <p class="fecha colortext ">Periodo y Gestión: <span class="colorestados"> {{ acta.perperiodo }}</span></p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-3 col-12 text-center">
                        <p class="fecha colortext ">Numero Acta: <span class="colorestados">{{ acta.acta }}</span></p>
                    </div >
                    <div class="col-lg-4 col-12 text-center">
                        <p class="fecha colortext ">Facultad: {{ acta.get_facultad_display }}</p>
                    </div>
                    <div class="col-lg-4 col-12 text-center">
                        <p class="fecha colortext ">Carreta: {{ acta.get_carrera_display }}</p>
                    </div>
                </div>
                <p class="title colortext text-center">Título: {{ acta.titulo }}</p>
                <div class="row">
                    <div class="col-lg-5 col-12 text-center">
                        <p class="fecha colortext ">Tutur:<br> {{ acta.tutor.nombre }} {{ acta.tutor.apellido }}</p>
                    </div >
                    <div class="col-lg-3 col-6 text-center">
                        <p class="fecha colortext ">Modalidad:<br> {{ acta.modalidad }}</p>
                    </div>
                    <div class="col-lg-3 col-6 text-center">
                        <p class="fecha colortext ">Calificación:<br> <span class="colorestados">{{ acta.get_resultado_display }}</span></p>
                        
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-4 col-6 text-center">
                        <p class="fecha colortext ">1er. Tribunal:<br> {{ acta.jurado_1.nombre }} {{ acta.jurado_1.apellido }}</p>
                    </div >
                    <div class="col-lg-4 col-6 text-center">
                        <p class="fecha colortext ">2do. Tribunal:<br> {{ acta.jurado_2.nombre }} {{ acta.jurado_2.apellido }}</p>
                    </div>
                    <div class="col-lg-4 col-6 text-center">
                        <p class="fecha colortext ">3er. Tribunal:<br> {{ acta.jurado_3.nombre }} {{ acta.jurado_3.apellido }}</p>
                        
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-10 col-12 ">
                        <p class="fecha colortext ">1er. Observación:  <span class="colorestados fechas">{{ acta.observacion_1 }}</span></p>
                    </div >
                    <div class="col-lg-10 col-12 ">
                        <p class="fecha colortext ">2do. Observación:  <span class="colorestados fechas">{{ acta.observacion_2 }}</span></p>
                    </div>
                    <div class="col-lg-10 col-12 ">
                        <p class="fecha colortext ">3er. Observación:  <span class="colorestados fechas">{{ acta.observacion_3 }}</span></p>
                        
                    </div>
                </div>
                
            </div>
            <div class="col-md-3 pt-4 d-flex flex-column align-items-center">
                {% if acta.estudiante.imagen %}
                <div class="mb-5">
                    <img src="{{ acta.estudiante.imagen.url }}" class="imgrepo" alt="sin foto" />
                </div>
                {% else %}
                <div class="mb-3">
                    <img src="{% static 'img/SINFOTO.webp' %}" class="imgrepo" alt="" />
                </div>
                {% endif %}
                <h5 class="text colortext text-center">Estudiante:<br> {{ acta.estudiante.nombre }} {{ acta.estudiante.apellido }}</h5>
                {% if acta.pk %}
                <a class="btn btn-sm btn-dark fontII" href="{% url 'Pdf_ReporteActa' pk=acta.pk %}">General Reporte Acta</a>
                {% else %}
                <span>No Acta available</span>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
    
    <!-- Paginación -->
    <nav>
        <ul class="pagination">
            {% if actas.has_previous %}
                <li class="page-item"><a class="btn btn-sm btn-dark me-1" href="?page=1{% if query %}&q={{ query }}{% endif %}">Primero</a></li>
                <li class="page-item"><a class="btn btn-sm btn-dark" href="?page={{ actas.previous_page_number }}{% if query %}&q={{ query }}{% endif %}">Anterior</a></li>
            {% endif %}

            <li class="page-item active"><a class="btn btn-sm btn-light">{{ actas.number }}</a></li>

            {% if actas.has_next %}
                <li class="page-item"><a class="btn btn-sm btn-dark me-1" href="?page={{ actas.next_page_number }}{% if query %}&q={{ query }}{% endif %}">Siguiente</a></li>
                <li class="page-item"><a class="btn btn-sm btn-dark" href="?page={{ actas.paginator.num_pages }}{% if query %}&q={{ query }}{% endif %}">Último</a></li>
            {% endif %}
        </ul>
    </nav><br>
</div><br>
{% endblock %}

seg_mod_graduacion/templates/perfil/agregar_perfil.html
{% extends 'dashboard.html' %}
{% load crispy_forms_tags %}
{% block title %}Crear Form{% endblock %}
{% load static %}
{% block content %}

<div class="container no-gutters p-lg-5 p-3 fontI ">
  <div class="no-gutte container p-lg-4 p-3">
    <h1  class="text-center pb-2 fontI colortitle titlesuperior">AGREGAR NUEVO FORMULARIO PERFIL DE PROYECTO</h1>
    <article class="pb-3 colortext" >
      <form method="post" enctype="multipart/form-data" id="perfilForm" onsubmit="showConfirmationModal(event)">
        {% csrf_token %}
        {{ formp|crispy }}
        {% if formp.errors %}
        <div class="alert alert-danger">
            <ul>
                {% for field in formp %}
                    {% for error in field.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                {% endfor %}
            </ul>
        </div>
        {% endif %}
        {% if not form_disabled %}
        <br>
        <input name="" id="" class="btn btn-dark me-2 fontII" type="submit" value="Enviar Informacion" {% if form_disabled %}disabled{% endif %}>
        <a href="{% url 'dashboard' %}" class="btn btn-secondary fontII ">Cancelar</a>
        {% else %}
            <p class="text-end text colorestados">Formulario deshabilitado. Su Perfil de a sido "Aprobado" o Debes tener la investigación "Aprobada" para agregar un perfil.</p>
        {% endif %}
      </form>
    </article>
  </div> 
</div><br>

<!-- Modal de confirmación -->
<div class="modal fade" id="confirmationModal" tabindex="-1" aria-labelledby="confirmationModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content bg-mdal">
      <div class="modal-header">
        <h5 class="modal-title font" id="confirmationModalLabel"> Confirmacion de Formulario</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body text-center font">
        <img src="{% static 'img/confi.png' %}" class="img-close" alt="" /><br>
        ¡Formulario Enviado con Exito!
      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>

<script>
  function showConfirmationModal(event) {
    event.preventDefault(); 
    console.log("Formulario enviado"); // Agregar esta línea para verificar
    $('#confirmationModal').modal('show'); 
    
    setTimeout(function() {
      $('#confirmationModal').modal('hide'); 
      document.getElementById("perfilForm").submit(); 
    }, 2000);
  }
</script>
{% endblock %}

seg_mod_graduacion/templates/perfil/editar_perfil.html
<!DOCTYPE html>
<html>
<head>
    <title>Editar Proyecto</title>
</head>
<body>
    <h1>Editar Proyecto: {{ proyecto.titulo }}</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar</button>
    </form>
</body>
</html>