administrador/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # ADMIN-DJANGO
    path('admin/', admin.site.urls),

    # APLICACION USUARIO
    path('', include('gestion_usuarios.urls')),

    # APLICACION REPOSITORIO DE TITULADOS
    path('', include('repositoriotitulados.urls')),
    
    # APLICACION SEG_MOD_GRADUACION
    path('', include('seg_mod_graduacion.urls')),
    
    # APLICACIION INTERACCION SOCIAL
    path('', include('interaccion_social.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

seg_mod_graduacion/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler403
from .views import handle_permission_denied
from seg_mod_graduacion import views
from .views import ModalidadCreateView, ModalidadListView, ModalidadUpdateView, Pdf_ReporteActaPrivada, Pdf_ReporteActaPublica
from .views import pdf_reporteinv,Pdf_Reporte_InvFiltrado, Pdf_Reporte_Perfiles, Pdf_ReporteActa

urlpatterns = [    
    #segguimiento modalidad de graduacion investigacion cientifica
    path('invcientifica/agregar_investigacion/', views.agregar_investigacion, name='agregar_investigacion'),
    path('invcientifica/vista_investigacion/',views.vista_investigacion, name='vista_investigacion'),
    path('invcientifica/ProyectosParaAprobar/', views.ProyectosParaAprobar.as_view(), name='ProyectosParaAprobar'),
    path('AprobarProyecto/<int:proyecto_id>/', views.AprobarProyecto.as_view(), name='AprobarProyecto'),
    path('RechazarProyecto/<int:proyecto_id>/', views.RechazarProyecto.as_view(), name='RechazarProyecto'),
    path('invcientifica/global_settings/', views.global_settings_view, name='global_settings'),
    path('listarinvcientifica/', views.listarinvcientifica, name='listarinvcientifica'),
    path('pdf_reporteinv/<int:pk>/', pdf_reporteinv.as_view(), name='pdf_reporteinv'),
    path('Pdf_Reporte_InvFiltrado', Pdf_Reporte_InvFiltrado.as_view(), name='Pdf_Reporte_InvFiltrado'),
    
    #seguimiento modalidad de graduacion perfil de proyecto
    path('perfil/agregar_perfil/', views.agregar_perfil, name='agregar_perfil'),
    path('perfil/vista_perfil/',views.vista_perfil, name='vista_perfil'),
    path('perfil/PerfilesParaAprobar/', views.PerfilesParaAprobar.as_view(), name='PerfilesParaAprobar'),
    path('AprobarPerfil/<int:proyecto_id>/', views.AprobarPerfil.as_view(), name='AprobarPerfil'),
    path('RechazarPerfil/<int:proyecto_id>/', views.RechazarPerfil.as_view(), name='RechazarPerfil'),
    path('agregar-acta/', views.agregar_actaperfil, name='agregar_actaperfil'),
    path('listarperfiles/', views.listarperfiles, name='listarperfiles'),
    path('reporte-perfiles-pdf/', Pdf_Reporte_Perfiles.as_view(), name='Pdf_Reporte_Perfiles'),
    path('perfil/astas_list', views.actaperfil_list, name='actaperfil_list'),
    path('reporte_acta/<int:pk>/', Pdf_ReporteActa.as_view(), name='Pdf_ReporteActa'),
    
    #seguimiento modalidad de graduacion proyecto final
    path('controlador/actividad_control/nueva/', views.crear_actividad_control, name='crear_actividad_control'),
    path('controlador/editar_actividad_control/<int:pk>/editar/', views.editar_actividad_control, name='editar_actividad_control'),
    path('controlador/lista_actividad_control/', views.lista_actividad_control, name='lista_actividad_control'),
    
    path('proyectofinal/revision/<int:actividad_id>/', views.revisar_actividad, name='revisar_actividad'),
    path('controlador/revision/<int:actividad_id>/', views.revision, name='revision'),
    
    path('controlador/listaractividades/', views.listaractividades, name='listaractividades'),
    path('controlador/listaactividades/', views.listaactividades, name='listaactividades'),
    
    path('proyectofinal/crear_actividad/nueva/', views.crear_actividad, name='crear_actividad'),
    path('proyectofinal/actividad/', views.lista_actividad, name='lista_actividad'),
    path('agregar-actaprivada/', views.agregar_actaprivada, name='agregar_actaprivada'),
    path('agregar-actapublica/', views.agregar_actapublica, name='agregar_actapublica'),
    path('buscar_estudiante_privada/', views.buscar_estudiante_privada, name='buscar_estudiante_privada'),
    path('buscar_estudiante_publica/', views.buscar_estudiante_publica, name='buscar_estudiante_publica'),
    path('buscar_estudiante_paractivar/', views.buscar_estudiante_paractivar, name='buscar_estudiante_paractivar'),
    path('proyectofinal/astas_list_privada', views.actaprivada_list, name='actaprivada_list'),
    path('proyectofinal/astas_list_publica', views.actapublica_list, name='actapublica_list'),
    path('reporte_acta_privada/<int:pk>/', Pdf_ReporteActaPrivada.as_view(), name='Pdf_ReporteActaPrivada'),
    path('reporte_acta_publica/<int:pk>/', Pdf_ReporteActaPublica.as_view(), name='Pdf_ReporteActaPublica'),
    
    path('modalidad/modalidadagregar/', ModalidadCreateView.as_view(), name='modalidadagregar'),
    path('modalidades/', ModalidadListView.as_view(), name='listarmodalidades'),
    path('modalidad/editarmodalidad/<int:pk>/', ModalidadUpdateView.as_view(), name='editarmodalidad'),
    
    path('reportes/home_reporte', views.home_reporte, name='home_reporte'),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler403 = handle_permission_denied

seg_mod_graduacion/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model
from datetime import date
from django.conf import settings
from django.core.exceptions import ValidationError  

User = get_user_model()

ESTADO_CHOICES = [
    ('Aprobado', 'Aprobado'),
    ('Pendiente', 'Pendiente'),
    ('Rechazado', 'Rechazado'),
]

FACULTAD_CHOICES = [
    ('INGENIERÍA Y TECNOLOGÍA', 'Ingeniería y Tecnología'),
    ('mas..', 'mas..'),
    # Agrega más opciones según sea necesario
]

CARRERA_CHOICES = [
   ('INGENIERÍA DE SISTEMAS', 'Ingeniería de Sistemas'),
    ('mas..', 'mas..'),
    # Agrega más opciones según sea necesario
]

RESULTADO_CHOICES = [
    ('Suficiente', 'Suficiente'),
    ('Insuficiente', 'Insuficiente'),
    ('Aprobado', 'Aprobado'),
    ('Reprobado', 'Reprobado'),
    ('Postergado', 'Postergado')
]

class Modalidad(models.Model):
    nombre = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    
    class Meta:
        verbose_name_plural = "Modalidades"
        verbose_name = "Modalidad"


    def __str__(self):
        return self.nombre

class InvCientifica(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Usuario relacionado')
    invtitulo = models.CharField(max_length=450, verbose_name='Agregar Titulo')
    slug = models.SlugField(unique=True)
    invfecha_creacion = models.DateTimeField(auto_now_add=True)
    invdescripcion = models.TextField(verbose_name='Agregar una Descripcion Breve', blank=True)
    invdocumentacion = models.FileField(upload_to='documento/investigacion', verbose_name='Agregar Documentacion', null=True, blank=True)
    investado = models.CharField(max_length=10, choices=ESTADO_CHOICES, default='Pendiente')
    
    class Meta:
        verbose_name_plural = "Investicaciones cientificas"
        verbose_name = "Investigacion cientifica"


    def __str__(self):
        return self.invtitulo

class ComentarioInvCientifica(models.Model):
    invcomentario = models.TextField(max_length=1000, help_text='', verbose_name='Ingrese Comentario Retroalimentativo')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    invfecha_post = models.DateTimeField(auto_now_add=True)
    invproyecto_relacionado = models.ForeignKey(InvCientifica, on_delete=models.CASCADE)
    invdocorregido = models.FileField(upload_to='documento/investigacion', verbose_name='Agregar Documentacion', null=True, blank=True)

    class Meta:
        verbose_name_plural = "Comentario InvCientifica"
        verbose_name = "Comentario Inv"
        ordering = ['-invfecha_post']

    def __str__(self):
        return self.invcomentario[:15] + '...' if len(self.invcomentario) > 15 else self.invcomentario

class HabilitarSeguimiento(models.Model):
    habilitarInv = models.BooleanField(default=True, verbose_name='Habilitar Formulario')
    
    class Meta:
        verbose_name_plural = "Habilitacion Inv"
        verbose_name = "Habilitar Inv"

    def __str__(self):
        return "Configuración Global"

class PerfilProyecto(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Usuario relacionado')
    pertitulo = models.CharField(max_length=450, verbose_name='Agregar Titulo Perfil')
    slug = models.SlugField(unique=True)
    perfecha_creacion = models.DateTimeField(auto_now_add=True)
    perdescripcion = models.TextField(verbose_name='Agregar una Descripcion', blank=True)
    perdocumentacion = models.FileField(upload_to='documento/perfil', verbose_name='Agregar Documentacion', null=True, blank=True)
    permodalidad = models.ForeignKey(Modalidad, on_delete=models.CASCADE, verbose_name='Seleccione Una Modalidad')
    perestado = models.CharField(max_length=10, choices=ESTADO_CHOICES, default='Pendiente')
    
    class Meta:
        verbose_name_plural = "Perfil de Proyectos"
        verbose_name = "Perfil Proyecto"

    def __str__(self):
        return self.pertitulo

class ComentarioPerfil(models.Model):
    percomentario = models.TextField(max_length=1000, help_text='', verbose_name='Ingrese Comentario Retroalimentativo')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    perfecha_post = models.DateTimeField(auto_now_add=True)
    perproyecto_relacionado = models.ForeignKey(PerfilProyecto, on_delete=models.CASCADE, related_name='comentarios')
    perdocorregido = models.FileField(upload_to='documento/perfil', verbose_name='Agregar Documentacion', null=True, blank=True)

    class Meta:
        verbose_name_plural = "Comentario Perfiles"
        verbose_name = "Comentario Perfil"
        ordering = ['-perfecha_post']

    def __str__(self):
        return self.percomentario[:15] + '...' if len(self.percomentario) > 15 else self.percomentario
 
class ActaGeneral(models.Model):
    perperiodo = models.CharField(max_length=50,null=True, blank=True )
    acta = models.CharField(max_length=30)
    facultad = models.CharField(max_length=100, choices=FACULTAD_CHOICES, default='INGENIERÍA Y TECNOLOGÍA')
    carrera = models.CharField(max_length=100, choices=CARRERA_CHOICES, default='INGENIERÍA DE SISTEMAS')
    estudiante = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='acta_estudiante', on_delete=models.CASCADE)
    titulo = models.CharField(max_length=450)
    lugar = models.CharField(max_length=50)
    fechadefensa = models.DateField(default=timezone.now)
    horainicio = models.TimeField()
    horafin = models.TimeField()
    tutor = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='acta_tutor', on_delete=models.CASCADE)
    jurado_1 = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='acta_jurado_1', on_delete=models.CASCADE)
    jurado_2 = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='acta_jurado_2', on_delete=models.CASCADE)
    jurado_3 = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='acta_jurado_3', on_delete=models.CASCADE)
    modalidad = models.ForeignKey('Modalidad', on_delete=models.CASCADE, verbose_name='Seleccione Una Modalidad')
    resultado = models.CharField(max_length=15, choices=RESULTADO_CHOICES, default='Suficiente')
    observacion_1 = models.TextField(max_length=200)
    observacion_2 = models.TextField(max_length=200)
    observacion_3 = models.TextField(max_length=200)
    
    class Meta:
        verbose_name_plural = "Actas Base General"
        verbose_name = "Base Actas"
        
    def __str__(self):
        return self.acta
    
class ActaProyectoPerfil(ActaGeneral):
    pass
    
    class Meta:
        verbose_name_plural = "Actas Defensa Perfiles"
        verbose_name = "Acta Perfil"
        
    def save(self, *args, **kwargs):
        # Aquí no llamas a super().save() si no quieres que ActaGeneral se guarde
        # Asegúrate de manejar la lógica de guardado necesaria solo para ActaPrivada
        if not self.pk:  # Es una nueva instancia
            self.acta = f"Perfil-{self.acta}"  # Personaliza según tu lógica
        super(ActaGeneral, self).save(*args, **kwargs)

class ActaPrivada(ActaGeneral):
    calificacion1 = models.IntegerField()
    
    class Meta:
        verbose_name_plural = "Actas defensa Privada"
        verbose_name = "Acta Privada"
    
    def save(self, *args, **kwargs):
        # Aquí no llamas a super().save() si no quieres que ActaGeneral se guarde
        # Asegúrate de manejar la lógica de guardado necesaria solo para ActaPrivada
        if not self.pk:  # Es una nueva instancia
            self.acta = f"Privada-{self.acta}"  # Personaliza según tu lógica
        super(ActaGeneral, self).save(*args, **kwargs)
    
class ActaPublica(ActaGeneral):
    calificacion1 = models.IntegerField()
    calificacion2 = models.IntegerField()
    notatotal = models.IntegerField()
    presidenteacta = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='acta_presidente_Asig', on_delete=models.CASCADE)
    
    class Meta:
        verbose_name_plural = "Actas Defensa Publica"
        verbose_name = "Acta Publica"
    
    def save(self, *args, **kwargs):
        # Aquí no llamas a super().save() si no quieres que ActaGeneral se guarde
        # Asegúrate de manejar la lógica de guardado necesaria solo para ActaPrivada
        if not self.pk:  # Es una nueva instancia
            self.acta = f"Publica-{self.acta}"  # Personaliza según tu lógica
        super(ActaGeneral, self).save(*args, **kwargs)

class HabilitarProyectoFinal(models.Model):
    estudiante = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='actividad_estudiante', on_delete=models.CASCADE)
    tutor = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='actividad_tutor', on_delete=models.CASCADE)
    jurado_1 = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='actividad_jurado_1', on_delete=models.CASCADE)
    jurado_2 = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='actividad_jurado_2', on_delete=models.CASCADE)
    jurado_3 = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='actividad_jurado_3', on_delete=models.CASCADE)
    modalidad = models.ForeignKey(Modalidad, on_delete=models.CASCADE,  verbose_name='Seleccione Una Modalidad')

    def habilitar_actividad(self):
        actividad, created = ProyectoFinal.objects.get_or_create(
            estudiante=self.estudiante,
            defaults={
                'tutor': self.tutor,
                'jurado_1': self.jurado_1,
                'jurado_2': self.jurado_2,
                'jurado_3': self.jurado_3,
                'modalidad': self.modalidad,
                'habilitada': True
            }
        )
        if not created:
            actividad.tutor = self.tutor
            actividad.jurado_1 = self.jurado_1
            actividad.jurado_2 = self.jurado_2
            actividad.jurado_3 = self.jurado_3
            actividad.modalidad = self.modalidad
            actividad.habilitada = True

seg_mod_graduacion/templates/actas/agregar_actapublica.html
{% extends 'dashboard.html' %}
{% load crispy_forms_tags %}
{% block title %}Crear Form{% endblock %}
{% load static %}
{% block content %}

<div class="container no-gutters p-lg-5 p-3 font ">
  <div class="no-gutte container p-lg-5 p-3">
    <h1 class="text-center pb-2 titlesuperior">LLENADO DE ACTA DEFENSA PUBLICA</h1>
    
    <article class="pb-2 colortext" >
      <form id="pot" method="post" enctype="multipart/form-data" onsubmit="showConfirmationModal(event)">
        {% csrf_token %}
        <div class="fechas fontI">
            <div class="row mb-3">
              <div class="col-md-3 pt-1">
                {{ form.facultad.label_tag }}<br>{{ form.facultad }}
                {% if form.facultad.errors %}
                  <div class="text-danger">{{ form.facultad.errors }}</div>
                {% endif %}
              </div>
              <div class="col-md-3 pt-1">
                {{ form.carrera.label_tag }}<br>{{ form.carrera }}
                {% if form.carrera.errors %}
                  <div class="text-danger">{{ form.carrera.errors }}</div>
                {% endif %}
              </div>
              <div class="col-md-3 col-6 pt-1">
                {{ form.acta.label_tag }}<br>{{ form.acta }}
                {% if form.acta.errors %}
                  <div class="text-danger">{{ form.acta.errors }}</div>
                {% endif %}
              </div>
              <div class="col-md-3 col-6 pt-1">
                {{ form.perperiodo.label_tag }}<br>{{ form.perperiodo }}
                {% if form.perperiodo.errors %}
                  <div class="text-danger">{{ form.perperiodo.errors }}</div>
                {% endif %}
              </div>
            </div>
            <div class="row mb-3">
              <div class="col-md-4 pt-1">
                {{ form.estudiante.label_tag }}<br>{{ form.estudiante }}
                {% if form.estudiante.errors %}
                  <div class="text-danger">{{ form.estudiante.errors }}</div>
                {% endif %}
              </div>
              <div class="col-md-4 pt-1">
                {{ form.tutor.label_tag }}<br>{{ form.tutor }}
                {% if form.tutor.errors %}
                  <div class="text-danger">{{ form.tutor.errors }}</div>
                {% endif %}
              </div>
              <div class="col-md-4 pt-1">
                {{ form.presidenteacta.label_tag }}<br>{{ form.presidenteacta }}
                {% if form.presidenteacta.errors %}
                  <div class="text-danger">{{ form.presidenteacta.errors }}</div>
                {% endif %}
              </div>
            </div>
            <div class="col-md-12 pt-1">
              {{ form.titulo.label_tag }}<br>{{ form.titulo }}
              {% if form.titulo.errors %}
                <div class="text-danger">{{ form.titulo.errors }}</div>
              {% endif %}
            </div>
            <div class="row mb-3 pt-2">
              <div class="col-md-3 pt-1">
                {{ form.lugar.label_tag }}<br>{{ form.lugar }}
                {% if form.lugar.errors %}
                  <div class="text-danger">{{ form.lugar.errors }}</div>
                {% endif %}
              </div>
              <div class="col-md-3 pt-1">
                {{ form.fechadefensa.label_tag }}<br>{{ form.fechadefensa }}
                {% if form.fechadefensa.errors %}
                  <div class="text-danger">{{ form.fechadefensa.errors }}</div>
                {% endif %}
              </div>
              <div class="col-md-3 pt-1">
                {{ form.horainicio.label_tag }}<br>{{ form.horainicio }}
                {% if form.horainicio.errors %}
                  <div class="text-danger">{{ form.horainicio.errors }}</div>
                {% endif %}
              </div>
              <div class="col-md-3 pt-1">
                {{ form.horafin.label_tag }}<br>{{ form.horafin }}
                {% if form.horafin.errors %}
                  <div class="text-danger">{{ form.horafin.errors }}</div>
                {% endif %}
              </div>
            </div>
            <div class="row mb-3">
              <div class="col-md-4 pt-1">
                {{ form.jurado_1.label_tag }}<br>{{ form.jurado_1 }}
                {% if form.jurado_1.errors %}
                  <div class="text-danger">{{ form.jurado_1.errors }}</div>
                {% endif %}
              </div>
              <div class="col-md-4 pt-1">
                {{ form.jurado_2.label_tag }}<br>{{ form.jurado_2 }}
                {% if form.jurado_2.errors %}
                  <div class="text-danger">{{ form.jurado_2.errors }}</div>
                {% endif %}
              </div>
              <div class="col-md-4 pt-1">
                {{ form.jurado_3.label_tag }}<br>{{ form.jurado_3 }}
                {% if form.jurado_3.errors %}
                  <div class="text-danger">{{ form.jurado_3.errors }}</div>
                {% endif %}
              </div>
            </div>
            <div class="row mb-3">
              <div class="col-md-3 pt-1">
                {{ form.modalidad.label_tag }}<br>{{ form.modalidad }}
                {% if form.modalidad.errors %}
                  <div class="text-danger">{{ form.modalidad.errors }}</div>
                {% endif %}
              </div>
              <div class="col-md-3 pt-1">
                {{ form.resultado.label_tag }}<br>{{ form.resultado }}
                {% if form.resultado.errors %}
                  <div class="text-danger">{{ form.resultado.errors }}</div>
                {% endif %}
              </div>
              <div class="col-md-2 col-4 pt-1">
                {{ form.calificacion1.label_tag }}<br>
                <input type="number" id="id_calificacion1" name="calificacion1" value="{{ form.calificacion1.value }}" class="form-control" min="0" max="30">
                {% if form.calificacion1.errors %}
                  <div class="text-danger">{{ form.calificacion1.errors }}</div>
                {% endif %}
              </div>
            
              <div class="col-md-2 col-4 pt-1">
                {{ form.calificacion2.label_tag }}<br>
                <input type="number" id="id_calificacion2" name="calificacion2" value="{{ form.calificacion2.value }}" class="form-control" min="0" max="70">
                {% if form.calificacion2.errors %}
                  <div class="text-danger">{{ form.calificacion2.errors }}</div>
                {% endif %}
              </div>
            
              <div class="col-md-2 col-3 pt-1">
                {{ form.notatotal.label_tag }}<br>
                <input type="number" id="id_notatotal" name="notatotal" value="{{ form.notatotal.value }}" class="form-control" min="0" max="100">
                {% if form.notatotal.errors %}
                  <div class="text-danger">{{ form.notatotal.errors }}</div>
                {% endif %}
              </div>
            </div>
            <div class="row mb-3">
              <div class="col-md-4 pt-1">
                {{ form.observacion_1.label_tag }}<br>{{ form.observacion_1 }}
                {% if form.observacion_1.errors %}
                  <div class="text-danger">{{ form.observacion_1.errors }}</div>
                {% endif %}
              </div>
              <div class="col-md-4 pt-1">
                {{ form.observacion_2.label_tag }}<br>{{ form.observacion_2 }}
                {% if form.observacion_2.errors %}
                  <div class="text-danger">{{ form.observacion_2.errors }}</div>
                {% endif %}
              </div>
              <div class="col-md-4 pt-1">
                {{ form.observacion_3.label_tag }}<br>{{ form.observacion_3 }}
                {% if form.observacion_3.errors %}
                  <div class="text-danger">{{ form.observacion_3.errors }}</div>
                {% endif %}
              </div>
            </div>
          </div>
        <br>
        <input name="" id="" class="btn btn-dark me-2 fontII" type="submit" value="Enviar Informacion" {% if form_disabled %}disabled{% endif %}>
        <a class="btn btn-secondary fontII" href="{% url 'dashboard' %}">Cancelar</a>
      </form>
      <br>
    </article>
  </div> 
</div><br>


<!-- Modal de confirmación -->
<div class="modal fade" id="confirmationModal" tabindex="-1" aria-labelledby="confirmationModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content bg-mdal">
      <div class="modal-header">
        <h5 class="modal-title font" id="confirmationModalLabel"> Confirmacion de Formulario</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body text-center font">
        <img src="{% static 'img/confi.png' %}" class="img-close" alt="" /><br>
        ¡Formulario Enviado con Exito!
      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>

<script>
  document.getElementById('id_estudiante').addEventListener('change', function() {
    let estudianteId = this.value;  // Asume que id_estudiante es el id del campo de selección

    fetch(`/buscar_estudiante_publica?id=${estudianteId}`)
        .then(response => response.json())
        .then(data => {
            if (data) {
                document.getElementById('id_acta').value = data.acta;
                document.getElementById('id_titulo').value = data.titulo;
                document.getElementById('id_lugar').value = data.lugar;
                document.getElementById('id_tutor').value = data.tutor;
                document.getElementById('id_jurado_1').value = data.jurado_1;
                document.getElementById('id_jurado_2').value = data.jurado_2;
                document.getElementById('id_jurado_3').value = data.jurado_3;
                document.getElementById('id_modalidad').value = data.modalidad;
                document.getElementById('id_calificacion1').value = data.calificacion1 || '';
            }
        })
        .catch(error => console.error('Error:', error));
});

document.addEventListener('DOMContentLoaded', function() {
  function updateNotaTotal() {
      var calificacion1 = parseFloat(document.getElementById('id_calificacion1').value) || 0;
      var calificacion2 = parseFloat(document.getElementById('id_calificacion2').value) || 0;
      var notatotal = calificacion1 + calificacion2;
      document.getElementById('id_notatotal').value = notatotal;
  }

  document.getElementById('id_calificacion1').addEventListener('input', updateNotaTotal);
  document.getElementById('id_calificacion2').addEventListener('input', updateNotaTotal);
});


  function showConfirmationModal(event) {
    event.preventDefault(); 
    $('#confirmationModal').modal('show'); 
    
    setTimeout(function() {
      $('#confirmationModal').modal('hide'); 
      document.getElementById("pot").submit(); 
    }, 2000);
  }
</script>
{% endblock %}