administrador/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # ADMIN-DJANGO
    path('admin/', admin.site.urls),

    # APLICACION USUARIO
    path('', include('gestion_usuarios.urls')),

    # APLICACION REPOSITORIO DE TITULADOS
    path('', include('repositoriotitulados.urls')),
    
    # APLICACION SEG_MOD_GRADUACION
    path('', include('seg_mod_graduacion.urls')),
    
    # APLICACIION INTERACCION SOCIAL
    path('', include('interaccion_social.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

seg_mod_graduacion/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler403
from .views import handle_permission_denied
from seg_mod_graduacion import views
from .views import ModalidadCreateView, ModalidadListView, ModalidadUpdateView, Pdf_ReporteActaPrivada, Pdf_ReporteActaPublica
from .views import pdf_reporteinv,Pdf_Reporte_InvFiltrado, Pdf_Reporte_Perfiles, Pdf_ReporteActa

urlpatterns = [    
    #segguimiento modalidad de graduacion investigacion cientifica
    path('invcientifica/agregar_investigacion/', views.agregar_investigacion, name='agregar_investigacion'),
    path('invcientifica/vista_investigacion/',views.vista_investigacion, name='vista_investigacion'),
    path('invcientifica/ProyectosParaAprobar/', views.ProyectosParaAprobar.as_view(), name='ProyectosParaAprobar'),
    path('AprobarProyecto/<int:proyecto_id>/', views.AprobarProyecto.as_view(), name='AprobarProyecto'),
    path('RechazarProyecto/<int:proyecto_id>/', views.RechazarProyecto.as_view(), name='RechazarProyecto'),
    path('invcientifica/global_settings/', views.global_settings_view, name='global_settings'),
    path('listarinvcientifica/', views.listarinvcientifica, name='listarinvcientifica'),
    path('pdf_reporteinv/<int:pk>/', pdf_reporteinv.as_view(), name='pdf_reporteinv'),
    path('Pdf_Reporte_InvFiltrado', Pdf_Reporte_InvFiltrado.as_view(), name='Pdf_Reporte_InvFiltrado'),
    
    #seguimiento modalidad de graduacion perfil de proyecto
    path('perfil/agregar_perfil/', views.agregar_perfil, name='agregar_perfil'),
    path('perfil/vista_perfil/',views.vista_perfil, name='vista_perfil'),
    path('perfil/PerfilesParaAprobar/', views.PerfilesParaAprobar.as_view(), name='PerfilesParaAprobar'),
    path('AprobarPerfil/<int:proyecto_id>/', views.AprobarPerfil.as_view(), name='AprobarPerfil'),
    path('RechazarPerfil/<int:proyecto_id>/', views.RechazarPerfil.as_view(), name='RechazarPerfil'),
    path('agregar-acta/', views.agregar_actaperfil, name='agregar_actaperfil'),
    path('listarperfiles/', views.listarperfiles, name='listarperfiles'),
    path('reporte-perfiles-pdf/', Pdf_Reporte_Perfiles.as_view(), name='Pdf_Reporte_Perfiles'),
    path('perfil/astas_list', views.actaperfil_list, name='actaperfil_list'),
    path('reporte_acta/<int:pk>/', Pdf_ReporteActa.as_view(), name='Pdf_ReporteActa'),
    
    #seguimiento modalidad de graduacion proyecto final
    path('controlador/actividad_control/nueva/', views.crear_actividad_control, name='crear_actividad_control'),
    path('controlador/editar_actividad_control/<int:pk>/editar/', views.editar_actividad_control, name='editar_actividad_control'),
    path('controlador/lista_actividad_control/', views.lista_actividad_control, name='lista_actividad_control'),
    
    path('proyectofinal/revision/<int:actividad_id>/', views.revisar_actividad, name='revisar_actividad'),
    path('controlador/revision/<int:actividad_id>/', views.revision, name='revision'),
    
    path('controlador/listaractividades/', views.listaractividades, name='listaractividades'),
    path('controlador/listaactividades/', views.listaactividades, name='listaactividades'),
    
    path('proyectofinal/crear_actividad/nueva/', views.crear_actividad, name='crear_actividad'),
    path('proyectofinal/actividad/', views.lista_actividad, name='lista_actividad'),
    path('agregar-actaprivada/', views.agregar_actaprivada, name='agregar_actaprivada'),
    path('agregar-actapublica/', views.agregar_actapublica, name='agregar_actapublica'),
    path('buscar_estudiante_privada/', views.buscar_estudiante_privada, name='buscar_estudiante_privada'),
    path('buscar_estudiante_publica/', views.buscar_estudiante_publica, name='buscar_estudiante_publica'),
    path('buscar_estudiante_paractivar/', views.buscar_estudiante_paractivar, name='buscar_estudiante_paractivar'),
    path('proyectofinal/astas_list_privada', views.actaprivada_list, name='actaprivada_list'),
    path('proyectofinal/astas_list_publica', views.actapublica_list, name='actapublica_list'),
    path('reporte_acta_privada/<int:pk>/', Pdf_ReporteActaPrivada.as_view(), name='Pdf_ReporteActaPrivada'),
    path('reporte_acta_publica/<int:pk>/', Pdf_ReporteActaPublica.as_view(), name='Pdf_ReporteActaPublica'),
    
    path('modalidad/modalidadagregar/', ModalidadCreateView.as_view(), name='modalidadagregar'),
    path('modalidades/', ModalidadListView.as_view(), name='listarmodalidades'),
    path('modalidad/editarmodalidad/<int:pk>/', ModalidadUpdateView.as_view(), name='editarmodalidad'),
    
    path('reportes/home_reporte', views.home_reporte, name='home_reporte'),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler403 = handle_permission_denied

seg_mod_graduacion/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model
from datetime import date
from django.conf import settings
from django.core.exceptions import ValidationError  

User = get_user_model()

ESTADO_CHOICES = [
    ('Aprobado', 'Aprobado'),
    ('Pendiente', 'Pendiente'),
    ('Rechazado', 'Rechazado'),
]

FACULTAD_CHOICES = [
    ('INGENIERÍA Y TECNOLOGÍA', 'Ingeniería y Tecnología'),
    ('mas..', 'mas..'),
    # Agrega más opciones según sea necesario
]

CARRERA_CHOICES = [
   ('INGENIERÍA DE SISTEMAS', 'Ingeniería de Sistemas'),
    ('mas..', 'mas..'),
    # Agrega más opciones según sea necesario
]

RESULTADO_CHOICES = [
    ('Suficiente', 'Suficiente'),
    ('Insuficiente', 'Insuficiente'),
    ('Aprobado', 'Aprobado'),
    ('Reprobado', 'Reprobado'),
    ('Postergado', 'Postergado')
]

class Modalidad(models.Model):
    nombre = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    
    class Meta:
        verbose_name_plural = "Modalidades"
        verbose_name = "Modalidad"


    def __str__(self):
        return self.nombre

class InvCientifica(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Usuario relacionado')
    invtitulo = models.CharField(max_length=450, verbose_name='Agregar Titulo')
    slug = models.SlugField(unique=True)
    invfecha_creacion = models.DateTimeField(auto_now_add=True)
    invdescripcion = models.TextField(verbose_name='Agregar una Descripcion Breve', blank=True)
    invdocumentacion = models.FileField(upload_to='documento/investigacion', verbose_name='Agregar Documentacion', null=True, blank=True)
    investado = models.CharField(max_length=10, choices=ESTADO_CHOICES, default='Pendiente')
    
    class Meta:
        verbose_name_plural = "Investicaciones cientificas"
        verbose_name = "Investigacion cientifica"


    def __str__(self):
        return self.invtitulo

class ComentarioInvCientifica(models.Model):
    invcomentario = models.TextField(max_length=1000, help_text='', verbose_name='Ingrese Comentario Retroalimentativo')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    invfecha_post = models.DateTimeField(auto_now_add=True)
    invproyecto_relacionado = models.ForeignKey(InvCientifica, on_delete=models.CASCADE)
    invdocorregido = models.FileField(upload_to='documento/investigacion', verbose_name='Agregar Documentacion', null=True, blank=True)

    class Meta:
        verbose_name_plural = "Comentario InvCientifica"
        verbose_name = "Comentario Inv"
        ordering = ['-invfecha_post']

    def __str__(self):
        return self.invcomentario[:15] + '...' if len(self.invcomentario) > 15 else self.invcomentario

class HabilitarSeguimiento(models.Model):
    habilitarInv = models.BooleanField(default=True, verbose_name='Habilitar Formulario')
    
    class Meta:
        verbose_name_plural = "Habilitacion Inv"
        verbose_name = "Habilitar Inv"

    def __str__(self):
        return "Configuración Global"

class PerfilProyecto(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Usuario relacionado')
    pertitulo = models.CharField(max_length=450, verbose_name='Agregar Titulo Perfil')
    slug = models.SlugField(unique=True)
    perfecha_creacion = models.DateTimeField(auto_now_add=True)
    perdescripcion = models.TextField(verbose_name='Agregar una Descripcion', blank=True)
    perdocumentacion = models.FileField(upload_to='documento/perfil', verbose_name='Agregar Documentacion', null=True, blank=True)
    permodalidad = models.ForeignKey(Modalidad, on_delete=models.CASCADE, verbose_name='Seleccione Una Modalidad')
    perestado = models.CharField(max_length=10, choices=ESTADO_CHOICES, default='Pendiente')
    
    class Meta:
        verbose_name_plural = "Perfil de Proyectos"
        verbose_name = "Perfil Proyecto"

    def __str__(self):
        return self.pertitulo

class ComentarioPerfil(models.Model):
    percomentario = models.TextField(max_length=1000, help_text='', verbose_name='Ingrese Comentario Retroalimentativo')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    perfecha_post = models.DateTimeField(auto_now_add=True)
    perproyecto_relacionado = models.ForeignKey(PerfilProyecto, on_delete=models.CASCADE, related_name='comentarios')
    perdocorregido = models.FileField(upload_to='documento/perfil', verbose_name='Agregar Documentacion', null=True, blank=True)

    class Meta:
        verbose_name_plural = "Comentario Perfiles"
        verbose_name = "Comentario Perfil"
        ordering = ['-perfecha_post']

    def __str__(self):
        return self.percomentario[:15] + '...' if len(self.percomentario) > 15 else self.percomentario
 
class ActaGeneral(models.Model):
    perperiodo = models.CharField(max_length=50,null=True, blank=True )
    acta = models.CharField(max_length=30)
    facultad = models.CharField(max_length=100, choices=FACULTAD_CHOICES, default='INGENIERÍA Y TECNOLOGÍA')
    carrera = models.CharField(max_length=100, choices=CARRERA_CHOICES, default='INGENIERÍA DE SISTEMAS')
    estudiante = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='acta_estudiante', on_delete=models.CASCADE)
    titulo = models.CharField(max_length=450)
    lugar = models.CharField(max_length=50)
    fechadefensa = models.DateField(default=timezone.now)
    horainicio = models.TimeField()
    horafin = models.TimeField()
    tutor = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='acta_tutor', on_delete=models.CASCADE)
    jurado_1 = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='acta_jurado_1', on_delete=models.CASCADE)
    jurado_2 = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='acta_jurado_2', on_delete=models.CASCADE)
    jurado_3 = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='acta_jurado_3', on_delete=models.CASCADE)
    modalidad = models.ForeignKey('Modalidad', on_delete=models.CASCADE, verbose_name='Seleccione Una Modalidad')
    resultado = models.CharField(max_length=15, choices=RESULTADO_CHOICES, default='Suficiente')
    observacion_1 = models.TextField(max_length=200)
    observacion_2 = models.TextField(max_length=200)
    observacion_3 = models.TextField(max_length=200)
    
    class Meta:
        verbose_name_plural = "Actas Base General"
        verbose_name = "Base Actas"
        
    def __str__(self):
        return self.acta
    
class ActaProyectoPerfil(ActaGeneral):
    pass
    
    class Meta:
        verbose_name_plural = "Actas Defensa Perfiles"
        verbose_name = "Acta Perfil"
        
    def save(self, *args, **kwargs):
        # Aquí no llamas a super().save() si no quieres que ActaGeneral se guarde
        # Asegúrate de manejar la lógica de guardado necesaria solo para ActaPrivada
        if not self.pk:  # Es una nueva instancia
            self.acta = f"Perfil-{self.acta}"  # Personaliza según tu lógica
        super(ActaGeneral, self).save(*args, **kwargs)

class ActaPrivada(ActaGeneral):
    calificacion1 = models.IntegerField()
    
    class Meta:
        verbose_name_plural = "Actas defensa Privada"
        verbose_name = "Acta Privada"
    
    def save(self, *args, **kwargs):
        # Aquí no llamas a super().save() si no quieres que ActaGeneral se guarde
        # Asegúrate de manejar la lógica de guardado necesaria solo para ActaPrivada
        if not self.pk:  # Es una nueva instancia
            self.acta = f"Privada-{self.acta}"  # Personaliza según tu lógica
        super(ActaGeneral, self).save(*args, **kwargs)
    
class ActaPublica(ActaGeneral):
    calificacion1 = models.IntegerField()
    calificacion2 = models.IntegerField()
    notatotal = models.IntegerField()
    presidenteacta = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='acta_presidente_Asig', on_delete=models.CASCADE)
    
    class Meta:
        verbose_name_plural = "Actas Defensa Publica"
        verbose_name = "Acta Publica"
    
    def save(self, *args, **kwargs):
        # Aquí no llamas a super().save() si no quieres que ActaGeneral se guarde
        # Asegúrate de manejar la lógica de guardado necesaria solo para ActaPrivada
        if not self.pk:  # Es una nueva instancia
            self.acta = f"Publica-{self.acta}"  # Personaliza según tu lógica
        super(ActaGeneral, self).save(*args, **kwargs)

class HabilitarProyectoFinal(models.Model):
    estudiante = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='actividad_estudiante', on_delete=models.CASCADE)
    tutor = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='actividad_tutor', on_delete=models.CASCADE)
    jurado_1 = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='actividad_jurado_1', on_delete=models.CASCADE)
    jurado_2 = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='actividad_jurado_2', on_delete=models.CASCADE)
    jurado_3 = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='actividad_jurado_3', on_delete=models.CASCADE)
    modalidad = models.ForeignKey(Modalidad, on_delete=models.CASCADE,  verbose_name='Seleccione Una Modalidad')

    def habilitar_actividad(self):
        actividad, created = ProyectoFinal.objects.get_or_create(
            estudiante=self.estudiante,
            defaults={
                'tutor': self.tutor,
                'jurado_1': self.jurado_1,
                'jurado_2': self.jurado_2,
                'jurado_3': self.jurado_3,
                'modalidad': self.modalidad,
                'habilitada': True
            }
        )
        if not created:
            actividad.tutor = self.tutor
            actividad.jurado_1 = self.jurado_1
            actividad.jurado_2 = self.jurado_2
            actividad.jurado_3 = self.jurado_3
            actividad.modalidad = self.modalidad
            actividad.habilitada = True

seg_mod_graduacion/templates/invcientifica/agregar_investigacion.html
{% extends 'dashboard.html' %}
{% load crispy_forms_tags %}
{% block title %}Crear Form{% endblock %}
{% load static %}
{% block content %}

<div class="container p-lg-5 p-3 fontI  no-gutters">
  <div class="no-gutte container p-lg-4 p-3 pb-2">
    <h1 class="text-center py-2  titlesuperior">AGREGAR NUEVO FORMULARIO ALCANCE DE PROYECTO</h1>
    {% if form_disabled %}
      <p class="text-end text colorestados ">El formulario de investigación está deshabilitado para el Usuario.</p>
    {% endif %}
    <article class="pb-3 colortext" >
      <form id="pot" method="post" enctype="multipart/form-data" onsubmit="showConfirmationModal(event)">
        {% csrf_token %}
        {{ form|crispy }}
        <br>
        <input name="" id="" class="btn btn-dark me-2 fontII" type="submit" value="Enviar Informacion" {% if form_disabled %}disabled{% endif %}>
        <a class="btn btn-secondary fontII" href="{% url 'dashboard' %}">Cancelar</a>
      </form>
      <br>
    </article>
  </div> 
</div><br>


<!-- Modal de confirmación -->
<div class="modal fade" id="confirmationModal" tabindex="-1" aria-labelledby="confirmationModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content bg-mdal">
      <div class="modal-header">
        <h5 class="modal-title font" id="confirmationModalLabel"> Confirmacion de Formulario</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body text-center font">
        <img src="{% static 'img/confi.png' %}" class="img-close" alt="" /><br>
        ¡Formulario Enviado con Exito!
      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>

<script>
  function showConfirmationModal(event) {
    event.preventDefault(); 
    $('#confirmationModal').modal('show'); 
    
    setTimeout(function() {
      $('#confirmationModal').modal('hide'); 
      document.getElementById("pot").submit(); 
    }, 2000);
  }
</script>
{% endblock %}

seg_mod_graduacion/templates/invcientifica/global_settings.html
{% extends 'dashboard.html'%} {% load static %} {% load crispy_forms_tags %}{% block content %}
<h1 class="text-center font">HABILITACIÓN DE FECHAS PARA PROYECTO INTERACION SOCIAL</h1>
<div class="container mt-3 pt-3">
  <div class="row pb-5 ">
    <div class="col-md-8  offset-md-2 pb-5">
      <div class="card contdoc">
        <div class="card-body font text-center">
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button class="btn btn-primary fontII" type="submit">Guardar</button>
                <a class="btn btn-danger fontII" href="{% url 'dashboard' %}">Camcelar</a>
            </form>
        </div>
        <br />
      </div>
    </div>
  </div>
</div>
{% endblock %}

seg_mod_graduacion/templates/invcientifica/vista_investigacion.html
{% extends 'dashboard.html' %}
{% load static %}
{% block content %}

<h1 class="text-center py-2 titlesuperior">VISTA Y ESTADO DE FORMULARIO INVESTIGACION CIENTIFICA</h1>
{% if proyectos %}
<div class="container mt-lg-2 mt-5">
  {% for proyecto in proyectos %}
  <div class="card narrow-card">
    <div class="row no-gutters">
      <!-- Foto en un lado -->
      {% if proyecto.user.imagen %}
        <div class="col-md-3 col-lg-3 centered-img">
            <img src="{{ proyecto.user.imagen.url }}" class="card-img imgperfil p-2" alt="{{ proyecto.user.username }}" />
        </div>
      {% else %}
        <div class="col-md-3 col-lg-3 centered-img">
            <img src="{% static 'img/SINFOTO.webp' %}" class="card-img imgperfil" alt="" />
        </div>
      {% endif %}
      
      <!-- Contenido en el otro lado -->
      <div class="col-md-7 col-lg-8 pb-5">
        <div class="card-body">
          <!-- Texto con formato pre -->
          <pre class="fecha fontI colorestados">                                                                                                 Enviado el : {{ proyecto.invfecha_creacion }}</pre>
          <!-- Título -->
          <h5 class="title pb-1 text-center fontI colortitle ">{{ proyecto.invtitulo }}</h5>
          <!-- Descripción -->
          <p class="fontI colortext">Descripción:<br>{{ proyecto.invdescripcion }}</p>
          <div class="container text-center">
            <div class="row">
              <div class="col-4 no-gutte py-2">
                <div class="d-flex align-items-center">
                  <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-file-earmark-richtext-fill" viewBox="0 0 16 16">
                    <path d="M9.293 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V4.707A1 1 0 0 0 13.707 4L10 .293A1 1 0 0 0 9.293 0M9.5 3.5v-2l3 3h-2a1 1 0 0 1-1-1M7 6.25a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0m-.861 1.542 1.33.886 1.854-1.855a.25.25 0 0 1 .289-.047l1.888.974V9.5a.5.5 0 0 1-.5.5H5a.5.5 0 0 1-.5-.5V9s1.54-1.274 1.639-1.208M5 11h6a.5.5 0 0 1 0 1H5a.5.5 0 0 1 0-1m0 2h3a.5.5 0 0 1 0 1H5a.5.5 0 0 1 0-1"/>
                  </svg>
                  <a href="{{ proyecto.invdocumentacion.url }}" class="list-group-item list-group-item-action">Documento Evaluar</a>
                </div>
              </div>
              <div class="col-8">
                <h5 class="estado fontI colorestados text-end">Estado Revisión: {{proyecto.investado}}</h5>
              </div>
            </div> 
          </div>
          <br>
          <!-- Espacio de comentarios -->
          <br />
          <!-- Botón para ver documento -->
          <h5 class="text fontI colortitle text-center">Comentarios Retroalimentativos</h5>
          {% for invcomentario in proyecto.comentarioinvcientifica_set.all %}
          <h6 class="text-end fontI  colorestados fechas ">
            {{ invcomentario.invfecha_post }} Por:  <span class="colortext fontI fecha">{{ invcomentario.user.nombre }} {{ invcomentario.user.apellido }}</span>
          </h6>
          <p class="comentario fontI colortext">Comentario:<br>{{ invcomentario.invcomentario }}</p>
          {% if invcomentario.invdocorregido %}
          <a href="{{ invcomentario.invdocorregido.url }}" target="_blank" class="text-decoration-none text-end fontI align-items-end colortext fechas contdoc p-2 ">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-send-check" viewBox="0 0 16 16">
              <path d="M15.964.686a.5.5 0 0 0-.65-.65L.767 5.855a.75.75 0 0 0-.124 1.329l4.995 3.178 1.531 2.406a.5.5 0 0 0 .844-.536L6.637 10.07l7.494-7.494-1.895 4.738a.5.5 0 1 0 .928.372zm-2.54 1.183L5.93 9.363 1.591 6.602z"/>
              <path d="M16 12.5a3.5 3.5 0 1 1-7 0 3.5 3.5 0 0 1 7 0m-1.993-1.679a.5.5 0 0 0-.686.172l-1.17 1.95-.547-.547a.5.5 0 0 0-.708.708l.774.773a.75.75 0 0 0 1.174-.144l1.335-2.226a.5.5 0 0 0-.172-.686"/>
            </svg> Documento Corregido 
          </a>
          {% else %}
          <p class="fontI  colortext fechas">Documento Adecuado <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-patch-check-fill" viewBox="0 0 16 16">
            <path d="M10.067.87a2.89 2.89 0 0 0-4.134 0l-.622.638-.89-.011a2.89 2.89 0 0 0-2.924 2.924l.01.89-.636.622a2.89 2.89 0 0 0 0 4.134l.637.622-.011.89a2.89 2.89 0 0 0 2.924 2.924l.89-.01.622.636a2.89 2.89 0 0 0 4.134 0l.622-.637.89.011a2.89 2.89 0 0 0 2.924-2.924l-.01-.89.636-.622a2.89 2.89 0 0 0 0-4.134l-.637-.622.011-.89a2.89 2.89 0 0 0-2.924-2.924l-.89.01zm.287 5.984-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 1 1 .708-.708L7 8.793l2.646-2.647a.5.5 0 0 1 .708.708"/>
          </svg></p>
          {% endif %}
          {% empty %}
          <p class="comentario fontI colortext">No hay comentarios para este proyecto.</p>
          {% endfor %}
        </div>
        <br>
      </div>
    </div>
  </div>
  <br>
  {% endfor %}
</div>

{% if proyectos.has_other_pages %}
<div class="pagination-container">
  <nav aria-label="Page navigation example">
    <ul class="pagination">
      {% if proyectos.has_previous %}
      <li class="page-item">
        <a class="page-link dark-link" href="?page=1">&laquo; Primero</a>
      </li>
      <li class="page-item">
        <a class="page-link dark-link" href="?page={{ proyectos.previous_page_number }}">Anterior</a>
      </li>
      {% endif %}
  
      <li class="page-item disabled">
        <a class="page-link dark-link">Página {{ proyectos.number }} de {{ proyectos.paginator.num_pages }}</a>
      </li>
  
      {% if proyectos.has_next %}
      <li class="page-item">
        <a class="page-link dark-link" href="?page={{ proyectos.next_page_number }}">Siguiente</a>
      </li>
      <li class="page-item">
        <a class="page-link dark-link" href="?page={{ proyectos.paginator.num_pages }}">Último &raquo;</a>
      </li>
      {% endif %}
    </ul>
  </nav>
</div>
{% endif %}
{% else %}
<p class="fecha fontI colorfechas pt-3">No hay proyectos asociados a este usuario. Consulta en la administración.</p>
{% endif %}
{% endblock %}